repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
  #- repo: https://github.com/pycqa/bandit
  #  rev: 1.7.4
  #  hooks:
  #  - id: bandit
  #    exclude: tests/

  # This pre commit only work with poetry so we commented it as we work with uv
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #  rev: v1.3.1
  #  hooks:
  #    - id: python-safety-dependencies-check
